import type { Metadata } from 'next';
import { Syne, Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/ui/navbar';
import Footer from '@/components/ui/footer';

const syne = Syne({
  subsets: [ 'latin' ],
  variable: '--font-syne',
  weight: [ '400', '500', '600', '700', '800' ],
  display: 'swap'
});

const inter = Inter({
  subsets: [ 'latin' ],
  variable: '--font-inter',
  weight: [ '400', '500', '600', '700', '800' ],
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${syne.variable} ${inter.variable}`}>
      <body className="bg-neutral-800 font-sans antialiased">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
